window.RIZZ_CONFIG = {
  shopUrl: "https://rizzvisuals.smugmug.com/Signature-Collection-1",
  email: "hello@rizzvisuals.com",
  works: [
    {id:"the-last-light",file:"21-the-last-light.jpg",title:"The Last Light",location:"Yosemite National Park, California",collection:"Yosemite",featured:true,position:"center 42%",story:"As the day’s final light swept across Half Dome, the granite glowed for only a few moments before fading into twilight. With the moon rising beside the summit, the familiar landscape became something quieter—a reminder that even iconic places are constantly changing.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"between-giants",file:"01-between-giants.jpg",title:"Between Giants",location:"Northern California Redwoods",collection:"Forest",featured:true,position:"center",story:"Morning light entered the redwoods in narrow bands, revealing the scale and stillness of the forest for only a few minutes. The scene felt less like a place being photographed and more like a space briefly opening.",medium:"Fine-art paper or metal",sizes:"Best at medium to large scale"},
    {id:"into-the-light",file:"02-hollow-giant.jpg",title:"Into the Light",location:"Northern California",collection:"Forest",featured:true,position:"center",story:"Sunlight broke through the mist and canopy, casting narrow beams across a quiet forest road. For a few minutes, an ordinary turn became a passage into light.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"winter-quiet",file:"03-ancient-canopy.jpg",title:"Winter Quiet",location:"Lake Tahoe, California",collection:"Landscape",featured:true,position:"center",story:"Snow softened the shoreline and surrounding peaks while the lake held nearly still. The scene felt suspended between seasons, stripped down to water, stone, trees, and winter light.",medium:"Fine-art paper or metal",sizes:"Best at medium to large scale"},
    {id:"hollow-giant",file:"04-into-the-light.jpg",title:"Hollow Giant",location:"Northern California Redwoods",collection:"Forest",featured:true,position:"center",story:"From inside the remains of an ancient redwood, the forest opens overhead through fire-scarred wood. The hollow trunk becomes both subject and frame—a record of survival shaped by time.",medium:"Fine-art paper",sizes:"Best in vertical formats"},
    {id:"fire-over-the-meadow",file:"05-fire-over-the-meadow.jpg",title:"Fire Over the Meadow",location:"California",collection:"Landscape",featured:true,position:"center",story:"Clouds ignited above the tree line while the land below remained quiet and dark. The contrast lasted only moments before the color drained from the sky.",medium:"Metal",sizes:"Best at large scale"},
    {id:"drop-in",file:"06-iridescence.jpg",title:"Drop In",location:"Mavericks · Half Moon Bay, California",collection:"Coast",featured:true,position:"center",story:"A surfer commits beneath the crest of a powerful winter swell while a rescue craft waits beyond the break. Scale, speed, and consequence meet in a single instant.",medium:"Metal or acrylic",sizes:"Best at large scale"},
    {id:"ancient-canopy",file:"07-framed-city.jpg",title:"Ancient Canopy",location:"Northern California Redwoods",collection:"Forest",featured:false,position:"center",story:"Looking upward along the weathered trunk reveals the redwood as living architecture. The surrounding trees converge toward the sky while the ancient center holds its scars in full view.",medium:"Fine-art paper or metal",sizes:"Best in vertical formats"},
    {id:"coastal-noir",file:"08-coastal-noir.jpg",title:"Coastal Noir",location:"Northern California Coast",collection:"Coast",featured:true,position:"center",story:"Marine fog erased the horizon and reduced the coast to shape, tone, and suggestion. The familiar edge of California became cinematic, uncertain, and almost anonymous.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"framed-city",file:"09-winter-quiet.jpg",title:"Framed City",location:"San Francisco, California",collection:"Urban",featured:true,position:"center",story:"The Transamerica Pyramid appears precisely within the Golden Gate Bridge tower, compressing two San Francisco icons into one deliberate frame.",medium:"Metal",sizes:"Best at medium to large scale"},
    {id:"iridescence",file:"10-drop-in.jpg",title:"Iridescence",location:"Yosemite National Park, California",collection:"Yosemite",featured:true,position:"center",story:"Sunlight caught high cloud droplets above a granite ridge, breaking into unexpected bands of color. For a brief moment, the Yosemite sky became the entire subject.",medium:"Metal or acrylic",sizes:"Best at medium to large scale"},
    {id:"beacon",file:"11-beacon.jpg",title:"Beacon",location:"Pigeon Point Lighthouse, California",collection:"Coast",featured:true,position:"center",story:"The lighthouse stands between land, sea, and night—a fixed point inside a landscape defined by movement. Its beam turns navigation into atmosphere.",medium:"Metal",sizes:"Best at medium to large scale"},
    {id:"cathedral-of-stars",file:"12-cathedral-of-stars.jpg",title:"Cathedral of Stars",location:"Northern California Coast",collection:"Night",featured:true,position:"center",story:"The night sky rose above the coast with enough clarity to make the shoreline feel small. Rock, water, and stars formed a temporary architecture of their own.",medium:"Metal or acrylic",sizes:"Best at large scale"},
    {id:"fogbound",file:"13-fogbound.jpg",title:"Fogbound",location:"Northern California",collection:"Landscape",featured:false,position:"center",story:"Fog compressed the distance until the landscape became a series of soft layers. What disappeared from view became as important as what remained.",medium:"Fine-art paper",sizes:"Best at medium scale"},
    {id:"point-reyes",file:"14-point-reyes.jpg",title:"Point Reyes",location:"Point Reyes, California",collection:"Coast",featured:false,position:"center",story:"Wind, distance, and exposed coastline define Point Reyes. The photograph holds the openness of the place without trying to tame it.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"white-wings",file:"15-white-wings.jpg",title:"White Wings",location:"Northern California",collection:"Wildlife",featured:true,position:"center",story:"A white bird lifted into the light with the landscape falling away behind it. The frame is less about identification than about movement, separation, and grace.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"night-current",file:"16-night-current.jpg",title:"Night Current",location:"San Francisco, California",collection:"Urban",featured:false,position:"center",story:"Long exposure turned traffic into flowing light, revealing the city as current rather than structure. The road appears to move even while the architecture remains fixed.",medium:"Metal",sizes:"Best in wide formats"},
    {id:"blue-hour",file:"17-blue-hour.jpg",title:"Blue Hour",location:"Northern California Coast",collection:"Coast",featured:false,position:"center",story:"After sunset, the coast settled into cool color and quiet water. The loudest part of the day had ended, leaving only the shape of the shoreline and the remaining light.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"moon-passage",file:"18-moon-passage.jpg",title:"Moon Passage",location:"Montara, California",collection:"Wildlife",featured:true,position:"center",story:"A quiet alignment of distance, timing, and chance. As the moon held above Montara, a formation of birds crossed its face and transformed a simple night sky into a fleeting passage.",medium:"Fine-art paper or metal",sizes:"Best at medium to large scale"},
    {id:"first-light",file:"19-first-light.jpg",title:"First Light",location:"California Sierra Nevada",collection:"Landscape",featured:true,position:"center",story:"The sun broke over a snow-covered ridge beneath violet storm clouds, briefly warming the frozen landscape before the day fully arrived.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"crossing-the-silence",file:"20-crossing-the-silence.jpg",title:"Crossing the Silence",location:"Golden Gate Bridge · San Francisco, California",collection:"Wildlife",featured:true,position:"center",story:"Marine fog softened the bridge until the structure nearly disappeared. A formation of pelicans crossed the opening at exactly the right height, turning a familiar landmark into a quiet wildlife moment.",medium:"Metal",sizes:"Best at large scale"}
  ]
};
