window.RIZZ_CONFIG = {
  shopUrl: "https://rizzvisuals.smugmug.com/Signature-Collection-1",
  email: "hello@rizzvisuals.com",
  works: [
    {id:"between-giants",file:"01-between-giants.jpg",title:"Between Giants",location:"Northern California Redwoods",collection:"Forest",featured:true,position:"center",story:"Morning light entered the redwoods in narrow bands, revealing the scale and stillness of the forest for only a few minutes. The scene felt less like a place being photographed and more like a space briefly opening.",medium:"Fine-art paper or metal",sizes:"Best at medium to large scale"},
    {id:"hollow-giant",file:"02-hollow-giant.jpg",title:"Hollow Giant",location:"Northern California Redwoods",collection:"Forest",featured:false,position:"center",story:"A living monument shaped by time, fire, weather, and survival. The hollow becomes both subject and frame, holding the viewer inside the history of the forest.",medium:"Fine-art paper",sizes:"Best at medium scale"},
    {id:"ancient-canopy",file:"03-ancient-canopy.jpg",title:"Ancient Canopy",location:"Northern California Redwoods",collection:"Forest",featured:false,position:"center",story:"Looking upward changes the forest completely. Trunks become lines, branches become architecture, and the canopy closes overhead like a natural cathedral.",medium:"Fine-art paper or metal",sizes:"Best in vertical formats"},
    {id:"into-the-light",file:"04-into-the-light.jpg",title:"Into the Light",location:"Northern California",collection:"Forest",featured:true,position:"center",story:"A dark forest road opened into a sudden wash of light. The photograph holds the tension between shadow and destination—the feeling of moving through uncertainty toward something briefly visible.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"fire-over-the-meadow",file:"05-fire-over-the-meadow.jpg",title:"Fire Over the Meadow",location:"California",collection:"Landscape",featured:true,position:"center",story:"Clouds ignited above the tree line while the land below remained quiet and dark. The contrast lasted only moments before the color drained from the sky.",medium:"Metal",sizes:"Best at large scale"},
    {id:"iridescence",file:"06-iridescence.jpg",title:"Iridescence",location:"Yosemite National Park, California",collection:"Yosemite",featured:true,position:"center",story:"High clouds caught the light and separated it into unexpected color above Yosemite. A familiar landscape became strange for a moment, shaped as much by the sky as by the granite below.",medium:"Metal or acrylic",sizes:"Best at medium to large scale"},
    {id:"framed-city",file:"07-framed-city.jpg",title:"Framed City",location:"San Francisco, California",collection:"Urban",featured:true,position:"center",story:"Bridge structure, distant skyline, and compressed perspective turned the city into a layered study of geometry. San Francisco appears less as a destination than as a shape held within another shape.",medium:"Metal",sizes:"Best in panoramic or large formats"},
    {id:"coastal-noir",file:"08-coastal-noir.jpg",title:"Coastal Noir",location:"Northern California Coast",collection:"Coast",featured:true,position:"center",story:"Marine fog erased the horizon and reduced the coast to shape, tone, and suggestion. The familiar edge of California became cinematic, uncertain, and almost anonymous.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"winter-quiet",file:"09-winter-quiet.jpg",title:"Winter Quiet",location:"California",collection:"Landscape",featured:false,position:"center",story:"Winter stripped the scene down to its essential forms. Without dramatic color or movement, the landscape asked for a slower kind of attention.",medium:"Fine-art paper",sizes:"Best at medium scale"},
    {id:"drop-in",file:"10-drop-in.jpg",title:"Drop In",location:"Mavericks, Half Moon Bay, California",collection:"Coast",featured:true,position:"center",story:"A surfer commits at the edge of a moving wall of water. Scale, speed, and consequence collapse into a single instant before the wave closes behind him.",medium:"Metal or acrylic",sizes:"Best at large scale"},
    {id:"beacon",file:"11-beacon.jpg",title:"Beacon",location:"Pigeon Point Lighthouse, California",collection:"Coast",featured:true,position:"center",story:"The lighthouse stands between land, sea, and night—a fixed point inside a landscape defined by movement. Its beam turns navigation into atmosphere.",medium:"Metal",sizes:"Best at medium to large scale"},
    {id:"cathedral-of-stars",file:"12-cathedral-of-stars.jpg",title:"Cathedral of Stars",location:"Northern California Coast",collection:"Night",featured:true,position:"center",story:"The night sky rose above the coast with enough clarity to make the shoreline feel small. Rock, water, and stars formed a temporary architecture of their own.",medium:"Metal or acrylic",sizes:"Best at large scale"},
    {id:"fogbound",file:"13-fogbound.jpg",title:"Fogbound",location:"Northern California",collection:"Landscape",featured:false,position:"center",story:"Fog compressed the distance until the landscape became a series of soft layers. What disappeared from view became as important as what remained.",medium:"Fine-art paper",sizes:"Best at medium scale"},
    {id:"point-reyes",file:"14-point-reyes.jpg",title:"Point Reyes",location:"Point Reyes, California",collection:"Coast",featured:false,position:"center",story:"Wind, distance, and exposed coastline define Point Reyes. The photograph holds the openness of the place without trying to tame it.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"white-wings",file:"15-white-wings.jpg",title:"White Wings",location:"Northern California",collection:"Wildlife",featured:true,position:"center",story:"A white bird lifted into the light with the landscape falling away behind it. The frame is less about identification than about movement, separation, and grace.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"night-current",file:"16-night-current.jpg",title:"Night Current",location:"San Francisco, California",collection:"Urban",featured:false,position:"center",story:"Long exposure turned traffic into flowing light, revealing the city as current rather than structure. The road appears to move even while the architecture remains fixed.",medium:"Metal",sizes:"Best in wide formats"},
    {id:"blue-hour",file:"17-blue-hour.jpg",title:"Blue Hour",location:"Northern California Coast",collection:"Coast",featured:false,position:"center",story:"After sunset, the coast settled into cool color and quiet water. The loudest part of the day had ended, leaving only the shape of the shoreline and the remaining light.",medium:"Fine-art paper or metal",sizes:"Best at medium scale"},
    {id:"moon-passage",file:"18-moon-passage.jpg",title:"Moon Passage",location:"Montara, California",collection:"Wildlife",featured:true,position:"center",story:"A quiet alignment of distance, timing, and chance. As the moon held above Montara, a formation of birds crossed its face and transformed a simple night sky into a fleeting passage.",medium:"Fine-art paper or metal",sizes:"Best at medium to large scale"},
    {id:"first-light",file:"19-first-light.jpg",title:"First Light",location:"Northern California",collection:"Wildlife",featured:true,position:"center",story:"At sunrise, the silhouette of a solitary bird became the anchor for the entire sky. The image depends on restraint: one subject, one horizon, and the first color of the day.",medium:"Metal or fine-art paper",sizes:"Best at medium to large scale"},
    {id:"crossing-the-silence",file:"20-crossing-the-silence.jpg",title:"Crossing the Silence",location:"Golden Gate Bridge · San Francisco, California",collection:"Wildlife",featured:true,position:"center",story:"Marine fog softened the bridge until the structure nearly disappeared. A formation of pelicans crossed the opening at exactly the right height, turning a familiar landmark into a quiet wildlife moment.",medium:"Metal",sizes:"Best at large scale"}
  ]
};
